import type { NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { useForm } from "react-hook-form";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
	const { data: session } = useSession();
	const { register, handleSubmit } = useForm<{ name: string }>();
	const { data: tasks } = trpc.useQuery(["tasks.findAll"]);
	const createTask = trpc.useMutation("tasks.create");

	const onSubmit = (data: { name: string }) => createTask.mutate(data);

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container">
				<button onClick={() => signIn()}>Sign in</button>
				{session?.user?.email}
			</main>

			<form onSubmit={handleSubmit(onSubmit)}>
				<input placeholder="Task name!" {...register("name")} />
				<input type="submit" />
			</form>

			{tasks ? tasks.map((task) => <div key={task.id}>{task.name}</div>) : null}
		</>
	);
};

export default Home;
