import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Revivios</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<button onClick={() => signIn()}>Sign in</button>
			</main>
		</>
	);
};

export default Home;
